#!/bin/bash

### BEGIN INIT INFO
# Provides:          fk-config-service-confd
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: Daemon for configuration
# Description:       Daemon which updates config files based 
#					 on watches on config service
### END INIT INFO

set -e

PACKAGE="fk-config-service-confd"
SERVICE=/etc/service/$PACKAGE
CONFD="/usr/share/$PACKAGE/bin/confd -onetime"

case $1 in
  start)
    svc -u $SERVICE
    ;;
  stop)
    svc -d $SERVICE
    ;;
  restart)
    svc -d $SERVICE
	sleep 1
    svc -u $SERVICE
    ;;
  force-reload)
	$CONFD
    ;;
  status)
    svstat $SERVICE
    #healthcheck || (echo 'healthcheck failed' && false)
    ;;
  init)
   $CONFD 
   ;;
  shell)
	exec setuidgid $PACKAGE bash
	;;
  *)
  echo "Usage $0 {start|stop|status}"
    ;;
esac
