#!/bin/bash
set -e

PACKAGE="fk-config-service-confd"
SERVICE=/etc/service/$PACKAGE
CONFD="/usr/share/$PACKAGE/bin/confd -onetime"

case $1 in
  start)
    svc -u $SERVICE
    ;;
  stop)
    svc -d $SERVICE
    ;;
  restart)
    svc -d $SERVICE
    svc -u $SERVICE
    ;;
  status)
    svstat $SERVICE
    #healthcheck || (echo 'healthcheck failed' && false)
    ;;
  init)
   $CONFD 
   ;;
  shell)
	exec setuidgid $PACKAGE bash
	;;
  *)
  echo "Usage $0 {start|stop|status}"
    ;;
esac
